apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: netflow
  annotations:
    metallb.universe.tf/loadBalancerIPs: "172.18.1.209"
spec:
  type: LoadBalancer
  selector:
    app: grafana
  ports:
    - name: http
      port: 80
      targetPort: 3000
